var jezyki = [
    "dzień dobry!"
    ,"Hello!"
    ,"Hola!"
    ,"Bonjour!"
    ,"hallo!"
    ,"Ahoj!"
    ,"zdravo!"
    ,"Olá!"
    ,"Salut!"
    ,"Përshëndetje!"
    ,"Salam!"
    ,"kaixo!"
    ,"kumusta!"
    ,"Bonghjornu!"
    ,"Hallo!"
    ,"saluton!"
    ,"Tere!"
    ,"Hei!"
    ,"Hoi!"
    ,"ola!"
    ,"bonjou!"
    ,"sannu!"
    ,"aloha!"
    ,"nyob zoo!"
    ,"Hej!"
    ,"Helló!"
    ,"Halló!"
    ,"Nnọọ!"
    ,"Halo!"
    ,"Dia dhuit!"
    ,"Ciao!"
    ,"halo!"
    ,"Slav!"
    ,"Salve!"
    ,"Sveiki!"
    ,"Salama!"
    ,"hello!"
    ,"Bongu!"
    ,"tena koutou!"
    ,"Moni!"
    ,"talofa!"
    ,"Halò!"
    ,"Lumela!"
    ,"mhoro!"
    ,"Hallå!"
    ,"Kamusta!"
    ,"Merhaba!"
    ,"Здрастуйте!"
    ,"Salom!"
    ,"xin chào!"
    ,"Helo!"
    ,"Mholweni!"
    ,"Pẹlẹ o!"
    ,"Sawubona!"
    ]